name: Cross Platform Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - v*
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      id: checkout

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Get dependencies and run test
      run: |
        go test -race ./...

    - name: Build
      if: startsWith(github.ref, 'refs/tags/')
      run: make -j releases

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: kt-v*
        draft: false
        prerelease: false
